### ISSUE TITLE
Blank lines in scss files

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [mrmlnc/vscode-csscomb#28]
Hello,

I'm experiencing blank lines between rules when i run CSSComb command on *.scss file.
Here's the scenario:
### before
```css
#right {
    margin-left: 302px;
    border-left: none;
    overflow: auto;

    > .ui-resizable-w {
        width: 1px;
        left: 0;
        background-color: #8d8d8d;
        border-right: 4px solid #fff;
        border-left: 4px solid #fff;
    }
}
```
### after
```css
#right
{
    overflow: auto;

    margin-left: 302px;

    border-left: none;

    > .ui-resizable-w
    {
        left: 0;

        width: 1px;

        border-right: 4px solid #fff;
        border-left: 4px solid #fff;
        background-color: #8d8d8d;
    }
}

```

Regards,
me
