### ISSUE TITLE
Unspecified error in mixn processing

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [mrmlnc/vscode-csscomb#29]
Hello, It's me again.

I've set up CSSComb to run on each filesave.
I have the following `mixins.scss` file defined:
```scss
@mixin floating-element() {
    border: 1px solid #d4d4d4;
    box-shadow: 0 0 20px -10px #000000;
}

@mixin get-subtable-colour($number) {
    $index: ($number % length($random-colours)) + 1;
    border-left: 2px solid unquote(nth($random-colours, $index));
}
```
when i save the file I'm getting the error in VSCode output console:
```
Parsing error: Please check the validity of the block starting from line #13



Gonzales PE version: 3.0.0-28
Syntax: scss
```
Same error happens when i manually run `CSSComb` command.
Please note, the file is 9 lines long, and the error message says `starting from line #13`.

Regards,
me
PS
---
My `.csscomb.json` file is as follows:
```json
{
    "remove-empty-rulesets": true,
    "always-semicolon": true,
    "color-case": "lower",
    "block-indent": "    ",
    "color-shorthand": false,
    "element-case": "lower",
    "eof-newline": false,
    "leading-zero": true,
    "quotes": "double",
    "space-before-colon": "",
    "space-after-colon": " ",
    "space-before-combinator": " ",
    "space-after-combinator": " ",
    "space-between-declarations": "\n",
    "space-before-opening-brace": " ",
    "space-after-opening-brace": "\n",
    "space-after-selector-delimiter": "\n",
    "space-before-selector-delimiter": "",
    "space-before-closing-brace": "\n",
    "strip-spaces": true,
    "tab-size": true,
    "unitless-zero": true,
    "vendor-prefix-align": true,
     "sort-order": [
        [
            "line-height",
            "position",
       (...)
            "-ms-filter:\\'progid:DXImageTransform.Microsoft.gradient",
            "text-shadow"
        ]
    ]
}
```
and the `settings.json` is :
```json
// Place your settings in this file to overwrite default and user settings.
{
    "csscomb.formatOnSave": true
}
```
