### ISSUE TITLE
Сломалось :(

### ISSUE THREAD

**Issue by Riim** [mrmlnc/vscode-csscomb#47]
Привет! Вчера плагин обновился и перестал работать. При less/sass синтаксисах просто не работает, при css-синтаксисе:
```
[CSSComb]

Parsing error: Please check the validity of the block starting from line #1

1*| 	& .edit-mailing-view__editor {
2 | 		padding: 10px 0;
3 | 		border: 1px solid hsl(0,0%,97%);

Gonzales PE version: 3.0.0-28
Syntax: css
```

Если убрать всякие `& `, то тоже не работает. Повторяется на разных проектах, в тч в которых ничего не менялось.

**Comment by mrmlnc** [comment]
Привет, 

Недавние изменения затронули лишь часть, отвечающую за определение конфига и не относились к работе самого плагина.

Есть возможность поделиться файлом, где не работает плагин? Можно здесь или на почту, указанную в профиле.

**Comment by Riim** [comment]
В общем-то на любом не работает, например такой:
```css
.edit-mailing-editor-section.opal-text-input {
	display: block;
	width: 100%;

	& .opal-text-input__input {
		font-size: 1.1rem; // должен переместиться в самый низ
		padding: 10px 26px;
		line-height: 1.5;
		border: 0;
		box-shadow: none;
		resize: none;
		background: transparent;
		color: hsl(0,0%,40%);
	}

	&[disabled] .opal-text-input__input {
		background: transparent;
	}
}
```

При запуске плагина файл помечается как изменённый, но изменений не происходит, хотя точно должны произойти.

Вот ещё один из проектов: https://github.com/Riim/opal-components .

**Comment by mrmlnc** [comment]
Каким образом подключается конфиг (глобальные настройки редактора, локальные для директории, файл или `csscomb.preset` с путём до файла настроек)? В моём окружении работает со следующими настройками:

![2016-12-12_14-04-18](https://cloud.githubusercontent.com/assets/7034281/21097087/e5e0b54e-c073-11e6-815d-b48835dda8ad.gif)

**Comment by Riim** [comment]
Вроде я просто бросал `.csscomb.json` в проекты и всё работало. В настройках пользователя:
```json
// Поместите параметры в этот файл, чтобы перезаписать параметры по умолчанию.
{
    "editor.fontSize": 15,
    "editor.rulers": [120],
    "editor.wordSeparators": "`~!@#$%^&*()=+[{]}\\|;:'\",.<>/?",
    "editor.insertSpaces": false,
    "editor.wrappingColumn": 120,

    "window.openFilesInNewWindow": false,
    "window.reopenFolders": "all",

    "files.trimTrailingWhitespace": false,

    "files.associations": {
        "*.html": "handlebars",
        "*.css": "less"
    },

    "typescript.validate.enable": true,
    "javascript.validate.enable": false,

    "explorer.autoReveal": false,
	"explorer.openEditors.visible": 0,
	"typescript.check.tscVersion": false,
	"git.confirmSync": false
}
```
Настройки окружения:
```json
{
	"typescript.tsdk": "./node_modules/typescript/lib"
}
```

**Comment by mrmlnc** [comment]
Пока я разбираюсь с проблемой, вы можете использовать предыдущие версии. Просто удаляете плагин, загружаете `.vsix` файл и устанавливаете его, используя:
![image](https://cloud.githubusercontent.com/assets/7034281/21097594/4f6f3d94-c076-11e6-9aa1-8f63829e4aec.png)

https://github.com/mrmlnc/vscode-csscomb/releases/tag/3.2.1

**Comment by Riim** [comment]
Спасибо, работает. `vscode-csscomb-3.2.5.vsix` работает, `vscode-csscomb-3.2.6.vsix` уже нет.

**Comment by mrmlnc** [comment]
Если есть время, то проверь у себя будущую 4-ую версию: https://github.com/mrmlnc/vscode-csscomb/releases/tag/4.0.0.

**Comment by Riim** [comment]
Вроде всё хорошо работает)

**Comment by mrmlnc** [comment]
Я обновлю пакет в ближайшее время. Спасибо за отзыв о проблеме! ❤️🐼

**Comment by Riim** [comment]
Привет.
При обновлении с 4.0.1 до 5.0.0 появляется ошибка:
```
SyntaxError: No one parser could not parse file. See log for more details: []
	at Object.parse (/Users/Riim/.vscode/extensions/mrmlnc.vscode-csscomb-5.0.0/node_modules/config-profiler/out/services/parser.js:41:15)
	at Object.<anonymous> (/Users/Riim/.vscode/extensions/mrmlnc.vscode-csscomb-5.0.0/node_modules/config-profiler/out/services/config.js:37:47)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/Riim/.vscode/extensions/mrmlnc.vscode-csscomb-5.0.0/node_modules/tslib/tslib.js:93:62)
	at <anonymous>
```
Она же в 5.1.0.
В 5.2.0 и 5.2.1 ошибок нет, но плагин просто не работает.

И ещё, я использую плагин с postcss (+ свой плагин для postcss), просто выделяю фрагмент так, чтобы в нём оказывался валидный css и применяю плагин
![Image](https://4.downloader.disk.yandex.ru/disk/b5b5018c10359ee49cf365190e114f900db949f3925087e745116bb9b126b0ef/5a459aa3/ObPNusslySg1DkKXVbAngzbt65WoBZ79e6WWdaq2IKN-dadbnAxFnwsIeO0_wZdunr-FzOZlMxFqnjJDFfAz6Q%3D%3D?uid=0&filename=2017-12-29_00-29-26.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=54245&hid=f694685724fdca8641bb1301a74cb3fd&media_type=image&tknv=v2&etag=6a24cf97e61a1683674f2d09692ad82d)

Всё работает, но если я меняю подсветку на postcss, то появляется ошибка: We do not support "postcss" syntax.
Сложно ли сделать чтобы плагин всё же пытался примениться при postcss подсветке и выдавал эту ошибку только если ему не удаётся распарсить css?

**Comment by mrmlnc** [comment]
Официально CSSComb не поддерживает PostCSS. Не знаю почему. С моей колокольни проблема одна – там зоопарк плагинов и синтаксис не зафиксирован.

Кажется, что ты можешь указать [csscomb.syntaxAssociations](https://github.com/mrmlnc/vscode-csscomb#csscombsyntaxassociations) и это поможет. Если нет, то я могу добавить опцию вроде `forceTryApply`, например.

**Comment by Riim** [comment]
Пробовал добавлять
```json
    "csscomb.syntaxAssociations": {
        "postcss": "css"
    },
```
Не помогает. Вроде раньше такой опции не было, я пока 4.0.1 использую. Может если 5.2.* починить, то и forceTryApply не понадобиться?)

**Comment by mrmlnc** [comment]
Расширение работает корректно со следующими настройками:

```json
{
	"csscomb.syntaxAssociations": {
		"postcss": "scss"
	}
}
```

На файле `styles.pcss`:

```scss
.edit-mailing-editor-section.opal-text-input {
	display: block;
	width: 100%;

	& .opal-text-input__input {
		font-size: 1.1rem; // должен переместиться в самый низ
		padding: 10px 26px;
		line-height: 1.5;
		border: 0;
		box-shadow: none;
		resize: none;
		background: transparent;
		color: hsl(0,0%,40%);
	}

	&[disabled] .opal-text-input__input {
		background: transparent;
	}
}
```

Версии:

* VS Code — `1.44.2`
* Extension — `5.3.0`
