### ISSUE TITLE
CSScomb fails when first line contains comment

### ISSUE THREAD

**Issue by jhildenbiddle** [mrmlnc/vscode-csscomb#84]
Using CSScomb 5.1.0 with VSCode 1.15.0.

A file with a comment on the first line will cause CSSComb to fail.

Examples:
```css
/* CSS Comment */
body {
    color: black;
    background: white;
}
```
```sass
// SASS Comment
body {
    color: black;
    background: white;
}
```

VSCode "Output" panel after running "CSSComb: Format Styles" command:
```
[CSSComb]

TypeError: Cannot read property 'is' of null
```

Adding an empty line before the comment avoids the error but results in two empty lines before the comment.

Before CSSComb (empty line before the comment):
```css
 
/* CSS Comment */
body {
    color: black;
    background: white;
}
```
```sass
 
// SASS Comment
body {
    color: black;
    background: white;
}
```

After CSSComb (two empty lines before the comment):
```css
 
 
/* CSS Comment */
body {
    background: white;
    color: black;
}
```
```sass
 
 
// SASS Comment
body {
    background: white;
    color: black;
}
```
