### ISSUE TITLE
@include inside a selector throws error

### ISSUE THREAD

**Issue by ed-jimmy** [mrmlnc/vscode-csscomb#88]
```scss
.btn
{
    display: inline-block;
    
    @include module-structure-default($padding: $btn-padding);

    text-align: center;
    vertical-align: middle;

    touch-action: manipulation;
    cursor: pointer;
    
    background-image: none; // Reset unusual Firefox-on-Android default style; see https://github.com/necolas/normalize.css/issues/214
    border: none;

    white-space: nowrap;

    user-select: none;

    @include modifier('small')
    {
        padding: $btn-padding-small-y $btn-padding-small-x;
        
        font-size: $font-size-small;
    }

    @include modifier('large')
    {
        padding: $btn-padding-large-y $btn-padding-large-x;
        
        font-size: $font-size-large;
    }

    @include modifier('fluid')
    {
        width: 100%;
        
        position: relative;
        
        margin-top: 15px;
        padding: 10px;
    
        text-align: center;
        
        h1, h2, h3, h4, p, i, span
        {
            display: block;
        
            margin-right: auto;
            margin-left: auto;
        }

        @include modifies-element('icon')
        {
            font-size: $font-size-h4;
        }

        @include modifies-element('copy')
        {   
            position: absolute;
            top: 0;
            right: 0;
        
            padding: 5px;
        }

        span
        {
            font-size: $font-size-h6;
        }
    }
}
```

It throws this error when I run csscomb

```
[CSSComb]

TypeError: Cannot read property 'is' of null
```
