### ISSUE TITLE
Not work with scss file

### ISSUE THREAD

**Issue by HienNguyenAsnet** [mrmlnc/vscode-csscomb#96]
This plugin not work with scss file for me.
VS code version v1.18.1
vscode-csscomb version v5.2.1

I run csscomb for scss file but nothing happen. I tried it with css file and it's work perfectly.

**Comment by mrmlnc** [comment]
You can show example (GIF/Video)? It works fine for me.

**Comment by HienNguyenAsnet** [comment]
[Video](https://youtu.be/v5LjGK-HBOE)

Below is my config
<img width="412" alt="screen shot 2017-11-20 at 10 10 38" src="https://user-images.githubusercontent.com/5277254/33000833-f6481fb8-cddc-11e7-92e5-36b29d55153b.png">

I use sublime text and sublime text csscomb to format the scss file before. I tried setup vs code but no luck vscode csscomb not work on scss file for me.

**Comment by HienNguyenAsnet** [comment]
Here is OS info
MacBook Pro (Retina, 13-inch, Early 2015)
OSX El Captain 10.11.6

**Comment by mrmlnc** [comment]
You have a configuration file for CSSComb in the settings or [files](https://github.com/mrmlnc/vscode-csscomb#custom-configuration)

**Comment by nnmrts** [comment]
More details from me:
Windows 10, vscode insider build and stable build
csscomb 4.2.0

config:
```json
{
  "csscomb.formatOnSave": true,
  "csscomb.syntaxAssociations": {
      "postcss": "scss"
  },
  "csscomb.preset": {
	"always-semicolon": true,
	"color-case": "lower",
	"block-indent": "\t",
	"color-shorthand": false,
	"element-case": "lower",
	"eof-newline": true,
	"leading-zero": true,
	"quotes": "double",
	"sort-order-fallback": "abc",
	"space-before-colon": "",
	"space-after-colon": " ",
	"space-before-combinator": " ",
	"space-after-combinator": " ",
	"space-between-declarations": "\n",
	"space-before-opening-brace": " ",
	"space-after-opening-brace": "\n",
	"space-after-selector-delimiter": "\n",
	"space-before-selector-delimiter": "",
	"space-before-closing-brace": "\n",
	"strip-spaces": true,
	"unitless-zero": true,
	"vendor-prefix-align": true,
        "sort-order": [
                // ....
        ]
    }
}
```

For me, csscomb stops working if the scss file has an @-rule or a scoped variable in it:

```scss
// doesn't work
#header {
        width: 100%;
        @include blackBg;
}

// doesn't work
#header {
        width: 100%;
        $headerHeight: 64px;
}

// does work
#header {
        width: 100%;
        height: $headerHeight;
}

// does work
#header {
        width: 100%;
        #{$bg}-color: blue
}
```
In the cases it doesn't work, vscode throws me an error to the csscomb extension output:

```
[CSSComb]

TypeError: a.match is not a function
```
